config/routes.rb
Rails.application.routes.draw do
  devise_for :installs

  resources :customers
  get "/", to: 'customers#home'
  get "/about", to: 'customers#about'
end

app/models/customer.rb
class Customer < ActiveRecord::Base
end

app/models/install.rb
class Install < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  # devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  validates_format_of :email, /\A([^\s]+)((?:[-a-z0-9]\.)[a-z]{2,})\z/i
end

app/models/user.rb
class User < ActiveRecord::Base
    validates_format_of :email, with: /\A([^\s]+)((?:[-a-z0-9]\.)[a-z]{2,})\z/i
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  before_action :set_customer, only: [:show, :edit, :update, :destroy]

  
  def home
    
  end
  def about


  end  
  
  # GET /customers
  # GET /customers.json
  def err


  end
  def index
    if install_signed_in?
    @customers = Customer.all

    else render :err
    end
  end

  # GET /customers/1
  # GET /customers/1.json
  def show
  end

  # GET /customers/new
  def new
    if install_signed_in?
    @customer = Customer.new

    else render :err
    end
  end

  # GET /customers/1/edit
  def edit
  end

  # POST /customers
  # POST /customers.json
  def create
    @customer = Customer.new(customer_params)

    respond_to do |format|
      if @customer.save
        format.html { redirect_to @customer, notice: 'Customer was successfully created.' }
        format.json { render :show, status: :created, location: @customer }
      else
        format.html { render :new }
        format.json { render json: @customer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /customers/1
  # PATCH/PUT /customers/1.json
  def update
    respond_to do |format|
      if @customer.update(customer_params)
        format.html { redirect_to @customer, notice: 'Customer was successfully updated.' }
        format.json { render :show, status: :ok, location: @customer }
      else
        format.html { render :edit }
        format.json { render json: @customer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /customers/1
  # DELETE /customers/1.json
  def destroy
    @customer.destroy
    respond_to do |format|
      format.html { redirect_to customers_url, notice: 'Customer was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_customer
      @customer = Customer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def customer_params
      params.require(:customer).permit(:name, :email, :phone, :address)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/views/customers/_form.html.erb
<%= form_for(@customer) do |f| %>
  <% if @customer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@customer.errors.count, "error") %> prohibited this customer from being saved:</h2>

      <ul>
      <% @customer.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :phone %><br>
    <%= f.text_field :phone %>
  </div>
  <div class="field">
    <%= f.label :address %><br>
    <%= f.text_field :address %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/customers/about.html.erb
<div class="alert alert-info alert-dismissible" role="alert">
  This is about page
  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
  <span aria-hidden="true">&times;</span>
  </button>
</div>

app/views/customers/edit.html.erb
<h1 style="color:white;">Edit Customer</h1>

<%= render 'form' %>

<%= button_to 'Show', @customer,class:"btn btn-primary",method: :get,style:"margin:8px;"%> 
<%= button_to 'Back', customers_path,class:"btn btn-primary",method: :get,style:"margin:8px;" %>

app/views/customers/err.html.erb
<div class="alert alert-danger alert-dismissible" role="alert">
  Error loading the page
  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
  <span aria-hidden="true">&times;</span>
  </button>
</div>

app/views/customers/index.html.erb
<h1 style="color:white;">Customers</h1>

<table class="table table-bordered table-light">
  <thead style="color:white;background-color:red;">
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Phone</th>
      <th>Address</th>
      <th colspan="3"><center>Operations</center></th>
    </tr>
  </thead>

  <tbody style="color:white;background-color:black;">
    <% @customers.each do |customer| %>
      <tr>
        <td><%= customer.name %></td>
        <td><%= customer.email %></td>
        <td><%= customer.phone %></td>
        <td><%= customer.address %></td>
        <td><%= button_to 'Show', customer,class:"btn btn-primary",method: :get %></td>
        <td><%= button_to 'Edit', edit_customer_path(customer),class:"btn btn-primary",method: :get %></td>
        <td><%= button_to 'Destroy', customer, method: :delete, data: { confirm: 'Are you sure?' },class:"btn btn-primary" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= button_to 'New Customer', new_customer_path,class:"btn btn-primary",method:"get" %>

app/views/customers/new.html.erb
<h1 style="color:white;">New Customer</h1>

<%= render 'form' %>

<%= button_to 'Back', customers_path,class:"btn btn-primary",method:"get" %>

app/views/customers/show.html.erb
<table class="table table-bordered table-light">
  <thead style="color:white;background-color:red;">
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Phone</th>
      <th>Address</th>
    </tr>
  </thead>

  <tbody style="color:white;background-color:black;">
      <tr>
        <td><%= @customer.name %></td>
        <td><%= @customer.email %></td>
        <td><%= @customer.phone %></td>
        <td><%= @customer.address %></td>
      </tr>
  </tbody>
</table>

<%= button_to 'Edit', edit_customer_path(@customer),method: :get,class:"btn btn-primary",style:"margin:8px;" %> 
<%= button_to 'Back', customers_path ,method: :get,class:"btn btn-primary",style:"margin:8px;" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MyinternshipProjectpod2</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <!-- Latest compiled and minified CSS -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
  
  <!-- jQuery library -->
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.3/jquery.min.js"></script>
  
  <!-- Latest compiled JavaScript -->
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
  <style>
  .navbar { 
  min-height: 50px; 
}
.navbar-custom {
  background-color:black;
    
    color: black;
}
.nav > li > a:hover{
    background-color:darkviolet;
}
body{
  background-image: url('https://media.istockphoto.com/id/1198591342/photo/diamond-still-life.jpg?b=1&s=170667a&w=0&k=20&c=NcPp5xdvuPuQP4bx-k_h0QB5VGwsH1hP9sxQS7jpmCU=');
  background-repeat:repeat;
  background-size:cover;
}
label,em,li{
  color:black;
}
.link-to-text-color{
  
color:white;
}
</style>

</head>
<body>
<div class="collapse navbar-collapse">
<nav class="navbar navbar-custom">
  <div class="container-fluid">
    <div class="navbar-header">
     <div class="active"> <a class="navbar-brand" style="color:white" href="/"><i class="fa fa-diamond"></i> <b>Caratlane</b></a></div>
    </div>
    
    <ul class="nav navbar-nav navbar-right" style="padding:2px;">
      <li><%= button_to 'Home',"http://localhost:3000",class:"btn btn-primary",method:"get", style:"margin:8px;"%></li>
      <li><%= button_to 'About',"http://localhost:3000/about",class:"btn btn-danger",method:"get",style:"margin:8px;" %></li>
      <% if install_signed_in? %>
      <li><%= button_to 'Customers',customers_path,class:"btn btn-danger",style:"margin:8px;",method:"get" %></li>
      <li><div class="nav-text" style="padding:14px;"> <%= current_install.email %></div></li>
      <li><%= button_to 'Sign out', destroy_install_session_path,:method => :delete,class: "btn btn-danger",style:"margin:8px;" %></li>
      
      
      <% else %>
      <li><%= button_to 'Login', new_install_session_path,class: "btn btn-danger",style:"margin:8px;" %></li>
      <li><%= button_to 'Sign-up', new_install_registration_path,class: "btn btn-danger",method:"get",style:"margin:8px;" %></li>
  <% end %>
    </ul>
    </div>
  
   
  </div>
</nav>
</div>


<%= yield %>

</body>
</html>